name: Output Information
on: 
  workflow_dispatch:
  push:
    branches:
      - feature
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Get Context Info
        run: echo "${{toJSON(github)}}"