name: Scenario 1
on: 
  [workflow_dispatch]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: lint
      run: npm run lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with: 
        name: Uploaded files
        path: |
           dist
           package.json
            
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm run test
