name: Scenario 1
on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: lint
      run: npm lint
    - name: Build
      run: npm build
    - name: Test
      run: npm test